### ISSUE TITLE
Please make a linux build

### ISSUE THREAD

**Issue by liberodark** [eliboa/TegraRcmGUI#6]
Hi,

Please make a linux build is great soft but is just on windows.

Cordialy

**Comment by eliboa** [comment]
Sorry it ain't gonna happen because [TegraRcmSmash](https://github.com/rajkosto/TegraRcmSmash) (TegraRcmGUI is just an UI program based on TegraRcmSmash ) is only available for Windows systems 😞
The smasher/injector for Linux is called [Fusee Laucher](https://github.com/reswitched/fusee-launcher) and afaik there's no GUI for it, yet.

**Comment by eliboa** [comment]
Hi @ooii. It is as simple as that 😁, you just need to have both Python3 and Pyusb module installed on your computer.
